name = "tally-train"
main = "index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "tally-train"
route = "traintally.com/*"
zone_id = "your-zone-id-here"

[env.staging]
name = "tally-train-staging" 